apiVersion: v1
kind: Service
metadata:
  name: springbootpoc
  labels: { app: springbootpoc }
spec:
  selector: { app: springbootpoc }
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
